on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
name: Publish to VSCode Marketplace
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Check that the code is valid Typescript
        run: yarn tsc

      - name: Check that the code passes linting
        run: yarn lint

      - name: Run package tests
        run: yarn test

      - name: Build the extension
        run: yarn build

      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: 'publish minor -p $VSCE_TOKEN'
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
